"""add_missing_cascades

Revision ID: e3a7eda5c7f1
Revises: 2b8a1adb7f4d
Create Date: 2026-06-21 15:05:48.100483
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_missing_cascades

Revision ID: e3a7eda5c7f1
Revises: 2b8a1adb7f4d
Create Date: 2026-06-21 15:05:48.100483
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a7eda5c7f1'
down_revision: Union[str, None] = '2b8a1adb7f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_budgets_category_id', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_transactions_category_id', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_account_id', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'financial_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('fk_transactions_account_id', 'transactions', 'financial_accounts', ['account_id'], ['id'])
    op.create_foreign_key('fk_transactions_category_id', 'transactions', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key('fk_budgets_category_id', 'budgets', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
